### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by pYr0x**
update to react 15

### CODE REVIEW

**Comment by pYr0x** [comment]
@BigAB can you release the new version on npm?

**Comment by BigAB** [comment]
@pYr0x Alrighty, v0.0.24 released to **npm**

**Comment by Alfredo-Delgado** [comment]
This was a big change that shouldn't have been a simple patch update. We're going to have to revert this.

**Comment by pYr0x** [comment]
@Alfredo-Delgado @m-mujica then pls make a major release for can-react. Revert a PR after 2 month is not acceptable.

**Comment by m-mujica** [comment]
@pYr0x we released 0.1.x with the changes in the dependencies (back to the old versions), if you stay using 0.0.x you should be fine. We'll work on get the dependencies up to date when we have some bandwidth.

**Comment by Alfredo-Delgado** [comment]
What @m-mujica said, but since @pYr0x brings up acceptability, who gave the ok to merge this? @BigAB ?

**Comment by pYr0x** [comment]
@m-mujica sorry, you are right, i made a patch release and it should really a minor release.

@Alfredo-Delgado in the hangouts we talked about governance. we dont adopt the governance yet, but we talked about tacit agreement. i didnt got any feedback. the last commit was on 24 May. updating the dependencies does not break any test, because there are not tests. 
you cant revert a commit that break **your** app. if i revert commits on canjs because it break my app i get into trouble.
if this repos is private for your app, so pls mark it as "not ready for production" or "work in progress". there is not readme or something that says that the dependencies must not be updated!

**Comment by BigAB** [comment]
Was there a breaking change? The CI didn't catch it? Do we need more/better tests?

It should have been minor release, okay that makes sense.

I think the standard way of dealing with those kinds of mistakes is to revert as a patch and then re-publish a bumped-version with the changes.

We did that backwards here, but oh well. For next time though.

**Comment by pYr0x** [comment]
@BigAB there a no tests for that repo.

**reverting reasong**
Revert dependencies upgrade made in PR #11
Before moving forward with those updates we need to make sure it does
not break the largest app currently written with can-react, for the time
being the upgrade to can-connect breaks some code.

**Comment by BigAB** [comment]
> @BigAB there a no tests for that repo.

Ha, well, that's something we should address too 😄

**Comment by Alfredo-Delgado** [comment]
@pYr0x It might be a good idea for all of us to hop in a hangout and discuss the purpose of this repo. I'd be interested in seeing how you've been using it and what features in 15.0.x you're missing.

**Comment by pYr0x** [comment]
@Alfredo-Delgado sure of course! 
a detailed changelog you can find here https://facebook.github.io/react/blog/2016/04/07/react-v15.html

i came in touch with this repos by maintaining https://github.com/stealjs/steal-react-jsx

**Pull request merged**
